#!/bin/sh
DEPLOY_DIR=/var/www/html/haniflix-app
SERVER_DEPLOY_DIR=/var/www/html/haniflix-app/backend
GIT_DIR=/root/haniflix.git
BRANCH_NAME=master

# Ensure the deployment directory exists
mkdir -p "$DEPLOY_DIR"

# Set the GIT_WORK_TREE environment variable
GIT_WORK_TREE="$DEPLOY_DIR"

# Update the deployment folder with the latest changes
git --work-tree="$DEPLOY_DIR" --git-dir="$GIT_DIR" checkout -f "$BRANCH_NAME"

# Navigate to the deployment folder
cd "$SERVER_DEPLOY_DIR"

# Install production dependencies
npm install --production

# Rebuild Docker containers
sudo docker compose up -d --build


# # Check for changes in frontend (building, but not rebuilding Docker)
# if git diff --name-only "$PREVIOUS_COMMIT" "$CURRENT_COMMIT" | grep -q "frontend"; then
#     cd /root/haniflix-app/frontend
#     npm install && npm run build
# fi

# # Check for changes in admin (building, but not rebuilding Docker)
# if git diff --name-only "$PREVIOUS_COMMIT" "$CURRENT_COMMIT" | grep -q "admin"; then
#     cd /root/haniflix-app/admin
#     npm install && npm run build
# fi
